- name: CHECKING FOR THE NEWEST VERSION AND IF NEW AVAILABLE - SAVING TO FILE "./update_files/o365_version_xxxxxxxxxx.txt"
  hosts: localhost
  tasks:
  - name: EXECUTING MODULE "check_O365_updates"
    check_O365_updates:
    register: version_result
  - debug: var=version_result

- name: CHECKING VARIABLES
  hosts: asa
  gather_facts: false
  tasks:
    - set_fact:
        var_object_type: "{{ hostvars[inventory_hostname].var_object_type }}"
        var_object_name: "{{ hostvars[inventory_hostname].var_object_name }}"
        var_allow_LAN: "{{ hostvars[inventory_hostname].var_allow_LAN }}"

- name: UPDATING ASA
  hosts: asa
  connection: network_cli
  gather_facts: false
  become_method: enable
  roles:
    - role: asa-O365
      var_version: "{{ hostvars['localhost']['version_result']['meta'] }}"
      
